repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: flake8
        additional_dependencies:
        - flake8-docstrings
-   repo: local
    hooks:
    -   id: black
        name: black
        language: python
        entry: black
        language_version: python3.8
        args: [--line-length=88, --exclude=.venv, .]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5
    hooks:
    -   id: autopep8
